version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kowl:
    image: quay.io/cloudhut/kowl:v1.4.0
    restart: on-failure
    hostname: kowl
    volumes:
      - ./config.yaml:/etc/kowl/config.yaml
    ports:
      - "8080:8080"
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka

  sensorconnect:
    image: scarjit/sensorconnect:latest
    restart: on-failure
    volumes:
      - ./ioddfiles/:/opt/ioddfiles/
    environment:
      - IP_RANGE=192.168.10.17/32
      - KAFKA_BOOSTRAP_SERVER=kafka:9092
      - TRANSMITTERID=12345
      - IODD_FILE_PATH=/opt/ioddfiles

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
